(define (rows m)
  (length m))
(define (cols m)
  (length (car m)))
(define (same-dim? a b)
  (and (= (rows a) (rows b))
       (= (cols a) (cols b))))
(define (matrix-add a b)
  (if (not (same-dim? a b))
      (begin
        (display "Matrix dimensions must be the same...\n")
        '())
      (map (lambda (rowa rowb)
             (map + rowa rowb))
           a b)))
(define (transpose m)
  (if (null? (car m))
      '()
      (cons (map car m)
            (transpose (map cdr m)))))
(define (dot-product v1 v2)
  (apply + (map * v1 v2)))
(define (matrix-mult a b)
  (if (not (= (cols a) (rows b)))
      (begin
        (display "incorrect dimensions for multiplication...\n")
        '())
      (let ((b^t (transpose b)))
        (map (lambda (row)
               (map (lambda (col)
                      (dot-product row col))
                    b^t))
             a))))
(define (print-matrix m)
  (if (null? m)
      (newline)
      (begin
        (display (car m))
        (newline)
        (print-matrix (cdr m)))))
(define a '((7 5 3)
            (6 3 2)))
(define b '((8 2 6)
            (4 7 5)))
(define c '((9 5)
            (6 2)
            (1 3)))
(display "\na+b:\n")
(print-matrix (matrix-add a b))
(display "\ntranspose a:\n")
(print-matrix (transpose a))
(display "\na*c:\n")
(print-matrix (matrix-mult a c))