(define dictionary
  '("scheme" "scala" "golang" "java" "ruby" "rust" "javascript" "python" "c++" "swift"))
(define (check-word word dict)
  (cond
    ((null? dict) #f)
    ((string=? word (car dict)) #t)
    (else (check-word word (cdr dict)))))
(define (spell-check word)
  (if (check-word word dictionary)
      (display "correct spelling\n")
      (begin
        (display "incorrect spelling\n")
        (display "did you mean:\n")
        (display (suggest word dictionary))
        (newline))))
(define (substring? sub str)
  (let ((len-sub (string-length sub))
        (len-str (string-length str)))
    (define (helper i)
      (cond
        ((> (+ i len-sub) len-str) #f)
        ((string=? sub (substring str i (+ i len-sub))) #t)
        (else (helper (+ i 1)))))
    (helper 0)))
(define (suggest word dict)
  (cond
    ((null? dict) '())
    ((substring? word (car dict))
     (cons (car dict)
           (suggest word (cdr dict))))
    (else
     (suggest word (cdr dict)))))
(display "java\n")
(spell-check "java")
(display "\npyth\n")
(spell-check "pyth")
(display "\nscript\n")
(spell-check "script")
(display "\nru\n")
(spell-check "ru")
(display "\ngol\n")
(spell-check "gol")
(display "\nschem\n")
(spell-check "schem")
(display "\nc++\n")
(spell-check "c++")
(display "\nswift\n")
(spell-check "swift")